# Generated by Django 5.1.4 on 2024-12-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_favourites_operation_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
